name: "🐛 Bug"
description: Found a bug? Report it!
title: "🐛 BUG"
projects: []
labels: ["Type: Bug"]
body:
- type: markdown
  attributes:
    value: "- Thank you for taking the time to report a bug! 😄 \n- Please try to spend some time to understand the bug and reproduce it.\n- Take a look at our template and try to add as much detail as possible.\n- The more details we have, easier it would be to fix it. \n- If any heading is not applicable, put `NA`\n- For additional information, write it in additional context.\n"
- type: textarea
  id: something_wrong
  attributes:
    label: "What went wrong? Problem description🤔"
    description: |
      - Please provide a detailed description of the issue you encountered. Be clear and concise in explaining what is not working as expected.
    placeholder: Please describe the issue you experienced in detail, including any relevant information or context.
  validations:
    required: true
- type: textarea
  id: reproduction_steps
  attributes:
    label: "Steps to Reproduce Issue"
    description: If possible, please share the steps to reproduce the issue.
    value: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See the error
    render: bash
- type: textarea
  id: actual_behavior
  attributes:
    label: "Actual Behavior"
    description: Please describe how the system behavior when you encountered the issue.
    placeholder: Please describe the behavior that you observed when encountering the issue.
- type: textarea
  id: expected_behavior
  attributes:
    label: "Expected Behavior"
    description: Please describe how you expected the system to behave when you encountered the issue.
    placeholder: Please describe the behavior that you expected to see when encountering the issue.
- type: dropdown
  id: frequency
  attributes:
    label: "Frequency of Occurrence"
    description: Please select the frequency of Occurrence
    multiple: false
    options:
    - Always
    - 3/10
    - 5/10
    - 8/10
  validations:
    required: false
- type: textarea
  id: screenshot
  attributes:
    label: "Screenshots"
    description: If applicable, add screenshots/video/gif to help explain your problem.
- type: textarea
  id: console
  attributes:
    label: "Console Logs"
    description: Please attach console logs.  
- type: input
  id: environment
  attributes:
    label: "Environment"
    description: You can specify your operating system and version, web browser and version, or any other software that may be related to the issue.
    placeholder: ex. Windows 10, Chrome 91.0.4472.124
  validations:
    required: false
- type: dropdown
  id: browsers
  attributes:
    label: "Browsers"
    description: What browser(s) are you seeing the problem on?
    multiple: true
    options:
    - Chrome
    - Firefox
    - Safari
    - Microsoft Edge
    - Opera
    - Brave
    - Other
  validations:
    required: false
- type: dropdown
  id: os
  attributes:
    label: "OS"
    description: Please select the operating system(s) on which you are experiencing the issue from the dropdown list provided.
    multiple: true
    options:
    - Windows
    - Linux
    - Mac
    - iOS
    - Android
    - Other
  validations:
    required: false
- type: textarea
  id: solution_proposed
  attributes:
    label: "Solution Proposed"
    description: If you have any ideas or suggestions for how to fix the issue you encountered, please provide them in this section.
    placeholder: Please describe any potential solutions or ideas you may have for fixing the issue.

- type: textarea
  id: additional_context
  attributes:
    label: "Additional Context"
    description: If you have any additional context or information that may help us understand the problem better, please provide it here.
    placeholder: This can include any relevant logs, error messages, or other information that may be useful in diagnosing the issue.
- type: textarea
  id: actual_reported
  attributes:
    label: "Actual Reporter"
    description: Please specify the name or email of the actual reporter of the issue if it's not observed by QA
    placeholder: Please specify the name or email of the actual reporter of the issue if it's not observed by QA
    render: bash
  validations:
    required: false
- type: checkboxes
  id: is_customer_reported
  attributes:
    label: "Is this issue reported by a Customer?"
    options:
    - label: "Yes"
      required: true
- type: markdown
  attributes:
    value: Thank you for taking the time to report the issue! 😄  We appreciate your help! 😄
